version: '3.4'
services:
  predictions:
    image: lrnstak-predictions:latest
    build:
      context: ./services/predictions-flask
    networks:
      - lrnstak
  trainer:
    image: lrntsak-trainer:latest
    build:
      context: ./services/trainer-flask
    networks:
      - lrnstak
  registry:
    image: lrnstak-registry:latest
    build:
      context: ./services/registry-flask
    volumes:
      - ./models:/app/models
    networks:
      - lrnstak
  cache:
    image: lrnstak-storage:latest
    build:
      context: ./services/cache-flask
    networks:
      - lrnstak
    depends_on:
      - redis-store
  redis-store:
    image: redis:latest
    networks:
      - lrnstak
  proxy:
    image: nginx:latest
    ports:
      - "5000:80"
    volumes:
      - ./conf/proxy-nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - lrnstak

networks:
  lrnstak:
