version: '3.4'
services:
  predictions:
    image: lrnstak-predictions:latest
    build:
      context: ./services/predictions-flask
    networks:
      - lrnstak
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5000/health').raise_for_status()"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 120s
  trainer1:
    image: lrntsak-trainer:latest
    build:
      context: ./services/trainer-flask
    networks:
      - lrnstak
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5000/health').raise_for_status()"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 120s
  trainer2:
    image: lrntsak-trainer:latest
    networks:
      - lrnstak
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5000/health').raise_for_status()"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 120s
  trainer3:
    image: lrntsak-trainer:latest
    networks:
      - lrnstak
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5000/health').raise_for_status()"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 120s
  registry:
    image: lrnstak-registry:latest
    build:
      context: ./services/registry-flask
    volumes:
      - ./models:/app/models
    networks:
      - lrnstak
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5000/health').raise_for_status()"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 120s
  yfinance:
    image: lrnstak-yfinance:latest
    build:
      context: ./services/yfinance-flask
    networks:
      - lrnstak
    depends_on:
      - cache
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5000/health').raise_for_status()"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 120s
  cache:
    image: lrnstak-storage:latest
    build:
      context: ./services/cache-flask
    networks:
      - lrnstak
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5000/health').raise_for_status()"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 120s
  redis:
    image: redis:latest
    networks:
      - lrnstak
  proxy:
    image: nginx:latest
    ports:
      - "5000:80"
    volumes:
      - ./conf/nginx-server.conf:/etc/nginx/nginx.conf
      - ./conf/nginx-proxy.conf:/etc/nginx/conf.d/default.conf
    networks:
      - lrnstak
    depends_on:
      cache:
        condition: service_healthy
      registry:
        condition: service_healthy
      trainer1:
        condition: service_healthy
      trainer2:
        condition: service_healthy
      trainer3:
        condition: service_healthy
      yfinance:
        condition: service_healthy
      predictions:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  lrnstak:
